[workspace]
authors = ["Rohit Goswami <rohit.goswami@epfl.ch>"]
channels = ["conda-forge"]
name = "mts-forge"
platforms = ["linux-64", "osx-arm64", "osx-64"]
version = "0.1.0"
description = "Forge for metatensor enabled software and tooling"

[tasks]

[dependencies]
rattler-build = ">=0.40.0,<0.42"
sccache = ">=0.10.0,<0.11"
