[workspace]
authors = ["Rohit Goswami <rohit.goswami@epfl.ch>"]
channels = ["https://conda.anaconda.org/metatensor", "https://prefix.dev/mts-forge", "conda-forge"]
name = "mts-forge"
platforms = ["linux-64", "osx-arm64", "osx-64"]
version = "0.1.0"
description = "Forge for metatensor enabled software and tooling"

[tasks]
#  --experimental for nompi in context
build = "rattler-build build --experimental --recipe "
# Cached build
# https://rattler.build/latest/tips_and_tricks/#using-sccache-or-ccache-with-rattler-build
build-sccache = "USE_SCCACHE=1 rattler-build build --experimental --no-build-id --recipe "
build-all-sccache = "USE_SCCACHE=1 rattler-build build --experimental --no-build-id --skip-existing=all --recipe-dir ."

[dependencies]
rattler-build = ">=0.40.0,<0.42"
conda-index = ">=0.6.0,<0.7"
