[workspace]
authors = ["Rohit Goswami <rohit.goswami@epfl.ch>"]
channels = ["conda-forge"]
name = "mts-forge"
platforms = ["linux-64", "osx-arm64", "osx-64", "noarch"]
version = "0.1.0"
description = "Forge for metatensor enabled software and tooling"

[tasks]
build = "rattler-build build --recipe "
# Cached build
# https://rattler.build/latest/tips_and_tricks/#using-sccache-or-ccache-with-rattler-build
bcc = "_CCACHE=1 rattler-build build --no-build-id --recipe "

[dependencies]
rattler-build = ">=0.40.0,<0.42"
sccache = ">=0.10.0,<0.11"
