context:
  version: "2.10.dev1"
  git_rev: "d12388b23ee71cd4c61d845db22697f95b9489c9"

package:
  name: plumed-metatensor
  version: ${{ version }}

source:
  git: https://github.com/plumed/plumed2.git
  rev: ${{ git_rev }}

build:
  skip:
    - macos
    - win
  script: build.sh

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - make
    - if: osx
      then:
        - llvm-openmp
  host:
    - boost-cpp
    - openmpi
    - fftw
    - gsl
    - openblas
    - zlib
    - libtorch
    - libmetatensor-torch >=0.5.0,<0.6.0
    - if: osx
      then:
        - llvm-openmp
  run:
    - boost-cpp
    - openmpi
    - gawk
    - libtorch
    - libmetatensor-torch >=0.5.0,<0.6.0
    - if: osx
      then:
        - llvm-openmp

tests:
  - script:
    - plumed info --root
    - plumed info --long-version
    - plumed-patch -h
    - plumed config has external_blas external_lapack fftw gsl zlib
    - $PREFIX/lib/plumed/plumed-runtime -h
    - test -f $PREFIX/lib/libplumed$SHLIB_EXT
    - test -f $PREFIX/lib/libplumedWrapper.a
    - test -f $PREFIX/lib/libplumedKernel$SHLIB_EXT
    - conda inspect linkages -p $PREFIX $PKG_NAME
    - if: osx
      then:
        - conda inspect objects -p $PREFIX $PKG_NAME

# about:
#   home: http://www.plumed.org/
#   license: LGPL-3.0
#   license_family: GPL
#   license_file: COPYING.LESSER
#   summary: 'Free energy calculations in molecular systems'
#   description: |
#     PLUMED is an open source library for free energy calculations in
#     molecular systems which works together with some of the most
#     popular molecular dynamics engines.
  # doc_url: https://www.plumed.org/doc
  # dev_url: https://github.com/plumed/plumed2

# extra:
#   recipe-maintainers:
#     - HaoZeke
#     - luthaf
